version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .

